apiVersion: v1
kind: Service
metadata:
  name: simplifyit-client-service
spec:
  type: NodePort
  selector:
    app: simplifyit-client
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
