apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplifyit-client
  labels:
    app: simplifyit-client
spec:
  selector:
    matchLabels:
      app: simplifyit-client
  template:
    metadata:
      labels:
        app: simplifyit-client
    spec:
      containers:
        - name: simplifyit-client
          image: simplifyit/client:v.0.0.4
          env:
            - name: REACT_APP_BACKEND_URL
              value: "192.168.49.2"
            - name: REACT_APP_BACKEND_PORT
              value: "31000"
          ports:
            - containerPort: 3000
