apiVersion: v1
kind: Service
metadata:
  name: simplifyit-server-service
spec:
  type: LoadBalancer
  selector:
    app: simplifyit-server
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 31000
