apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplifyit-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplifyit-mongodb
  template:
    metadata:
      labels:
        app: simplifyit-mongodb
    spec:
      containers:
        - name: simplifyit-mongodb
          image: mongo:latest
          args: ["--dbpath", "/data/db"]
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: simplifyit-mongodb-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: simplifyit-mongodb-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
                  optional: false
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: simplifyit-mongodb-secrets
                  key: MONGO_INITDB_DATABASE
                  optional: false
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: "simplifyit-mongodb-pv-storage"
              mountPath: "/data/db"
      volumes:
        - name: simplifyit-mongodb-pv-storage
          persistentVolumeClaim:
            claimName: simplifyit-mongodb-pv-claim
