apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplifyit-mongodb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
